# ═══════════════════════════════════════════════════════════════════════════
# procedures.py — Procedural skills checklists for The Differential
#
# Written in ORIGINAL wording from standard clinical practice. The steps are
# how the procedures are correctly performed; no checklist is copied verbatim
# from any commercial or institutional source. Safe for a public repo.
#
# IMPORTANT: these are STUDY AIDS. Local protocols vary (prep solutions, bottle
# order, volumes, consent specifics). Always check each against your faculty's
# own marking sheet before relying on it for an assessment.
#
# HOW TO ADD: "Category :: Procedure Name": [ "Step 1", "Step 2", ... ]
# ═══════════════════════════════════════════════════════════════════════════

BUILTIN_PROCEDURES = {

    # ─────────────────────────────────────────────────────────────────────
    # GROUP 1 — Bedside basics, infection control & injections
    # ─────────────────────────────────────────────────────────────────────

    "Bedside Basics :: Hand Hygiene": [
        "Remove wrist and hand jewellery; roll up sleeves (bare below the elbows)",
        "Wet hands with water before applying soap (or use alcohol gel if hands are visibly clean)",
        "Apply enough product to cover all surfaces",
        "Rub palm to palm",
        "Rub right palm over left dorsum with interlaced fingers, and vice versa",
        "Rub palm to palm with fingers interlaced",
        "Rub backs of fingers against opposing palms with fingers interlocked",
        "Rub each thumb clasped in the opposite palm, rotating",
        "Rub fingertips in the opposite palm, rotating",
        "Rinse hands with water (if washing); dry thoroughly with a single-use towel",
        "Use the towel to turn off the tap (if not hands-free)",
        "Ensure the whole process takes the recommended duration (40–60 s wash / 20–30 s gel)",
    ],

    "Bedside Basics :: Personal Protective Equipment (Gown & Eye Protection)": [
        "Perform hand hygiene before starting",
        "Put on the gown, tying it securely at the neck and waist",
        "Put on a fluid-resistant surgical mask (or respirator if indicated), moulding to the face",
        "Put on eye protection (goggles or visor)",
        "Put on gloves, ensuring they cover the cuffs of the gown",
        "After the task: remove gloves first (peel inside-out), then perform hand hygiene",
        "Remove the gown, rolling it inward away from the body, and discard",
        "Perform hand hygiene",
        "Remove eye protection from behind without touching the front",
        "Remove the mask from behind, not touching the front; discard",
        "Perform final hand hygiene",
    ],

    "Bedside Basics :: Vital Signs (Manual BP, HR, RR)": [
        "Wash hands; introduce yourself and confirm patient identity",
        "Explain that you will measure their blood pressure, pulse, and breathing; gain consent",
        "Ensure the patient is rested and comfortable, arm supported at heart level",
        "Select an appropriately sized BP cuff and apply it to the upper arm",
        "Palpate the radial pulse and inflate the cuff until it disappears (estimate systolic)",
        "Deflate, then place the stethoscope over the brachial artery",
        "Re-inflate ~20–30 mmHg above the estimated systolic",
        "Deflate slowly (2–3 mmHg/sec); note the first Korotkoff sound (systolic)",
        "Note the point where sounds disappear (diastolic); deflate fully",
        "Palpate the radial pulse for rate, rhythm, and character over 30–60 seconds",
        "Count the respiratory rate over a full 60 seconds (ideally without the patient noticing)",
        "Note effort, depth, and symmetry of breathing",
        "Thank the patient; wash hands",
        "Document the readings and report any abnormal values",
    ],

    "Bedside Basics :: Bedside Blood Glucose (BGL)": [
        "Wash hands; introduce yourself and confirm patient identity",
        "Explain the procedure and gain verbal consent",
        "Check the glucometer is calibrated and the test strips are in date",
        "Put on gloves",
        "Clean the chosen finger (side of the fingertip); allow to dry",
        "Insert a strip into the meter",
        "Use a single-use lancet to obtain a drop of blood from the side of the fingertip",
        "Apply the blood drop to the strip and wait for the reading",
        "Apply pressure to the puncture site with gauze",
        "Dispose of the lancet into the sharps bin and the strip into clinical waste",
        "Remove gloves and wash hands",
        "Document the result and act on it if abnormal",
    ],

    "Bedside Basics :: Venous Blood Gas (VBG) Sampling": [
        "Wash hands; introduce yourself and confirm patient identity",
        "Explain the procedure and gain verbal consent",
        "Gather equipment: gloves, tourniquet, alcohol wipe, blood gas syringe, gauze, sharps bin",
        "Put on gloves; apply the tourniquet and select a suitable vein",
        "Clean the site with an alcohol wipe and allow to dry",
        "Insert the needle bevel-up into the vein and collect the sample into the gas syringe",
        "Release the tourniquet; withdraw the needle and apply pressure",
        "Dispose of the needle immediately into the sharps bin",
        "Expel any air bubbles and cap the syringe; mix gently",
        "Remove gloves and wash hands",
        "Analyse promptly; document the result",
    ],

    "Bedside Basics :: Urine Pregnancy Test": [
        "Wash hands; confirm patient identity and explain the test",
        "Gain consent and ask the patient to provide a fresh urine sample",
        "Check the test kit is in date",
        "Put on gloves",
        "Apply urine to the test device per the kit instructions (dip or drop)",
        "Wait the specified development time",
        "Read the control and test lines within the valid time window",
        "Confirm the control line is present (test valid)",
        "Dispose of materials appropriately; remove gloves and wash hands",
        "Document and communicate the result sensitively",
    ],

    "Bedside Basics :: Urinalysis (Ward / Clinic Dipstick)": [
        "Wash hands; confirm patient identity and explain the test",
        "Obtain a fresh urine sample; check the dipstick bottle is in date",
        "Put on gloves",
        "Note the urine's colour and clarity",
        "Briefly immerse the dipstick, ensuring all pads are wetted",
        "Tap off excess urine against the container edge",
        "Hold horizontally and read each pad at its correct time against the bottle chart",
        "Interpret the findings (e.g. leucocytes, nitrites, protein, blood, glucose, ketones)",
        "Dispose of materials; remove gloves and wash hands",
        "Document and act on the findings",
    ],

    "Injections :: Intramuscular (IM) Injection": [
        "Wash hands; introduce yourself and confirm patient identity",
        "Confirm the drug, dose, route, and timing against the prescription",
        "Check for allergies and gain consent",
        "Gather and check equipment: drug, syringe, drawing-up and injecting needles, alcohol wipe, gauze, sharps bin",
        "Check the drug name, strength, and expiry; draw up the correct dose using aseptic technique",
        "Select an appropriate site (e.g. deltoid or ventrogluteal) and expose it",
        "Put on gloves; clean the site if local policy requires and allow to dry",
        "Stretch the skin; insert the needle at 90° with a swift action",
        "Aspirate if local policy requires, then inject slowly",
        "Withdraw the needle and apply gentle pressure with gauze",
        "Dispose of the sharp immediately into the sharps bin",
        "Remove gloves and wash hands",
        "Document the administration; monitor for adverse reactions",
    ],

    "Injections :: Subcutaneous (SC) Injection": [
        "Wash hands; introduce yourself and confirm patient identity",
        "Confirm the drug, dose, route, and timing against the prescription",
        "Check for allergies and gain consent",
        "Gather and check equipment: drug, syringe/pen, needle, alcohol wipe, gauze, sharps bin",
        "Check the drug name, strength, and expiry; draw up the correct dose if needed",
        "Select an appropriate site (e.g. abdomen, outer thigh, upper arm) and rotate sites",
        "Put on gloves; clean the site if local policy requires and allow to dry",
        "Pinch a skin fold; insert the needle at 45–90° depending on needle length and patient",
        "Inject slowly; release the skin fold",
        "Withdraw the needle and apply gentle pressure (do not rub)",
        "Dispose of the sharp immediately into the sharps bin",
        "Remove gloves and wash hands",
        "Document the administration",
    ],

    "Wound Care :: Wound Swab": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent; gather a sterile swab and transport medium, gloves",
        "Put on gloves",
        "If there is surface slough or pus, consider cleaning/irrigating first per local policy",
        "Rotate the swab over the wound bed, focusing on viable tissue (e.g. a zig-zag technique)",
        "Avoid contaminating the swab with surrounding skin",
        "Place the swab into the transport medium without touching the outside",
        "Label the specimen at the bedside",
        "Dispose of waste; remove gloves and wash hands",
        "Complete the request form with clinical details; send promptly",
    ],

    # ─────────────────────────────────────────────────────────────────────
    # GROUP 2 — Phlebotomy, vascular access & blood sampling
    # ─────────────────────────────────────────────────────────────────────

    "Phlebotomy & Vascular :: Venepuncture": [
        "Wash hands / apply alcohol gel and put on apron",
        "Introduce yourself by name and role",
        "Confirm patient identity (name, date of birth, and ID number or address)",
        "Explain the procedure and what it involves; ask about a preferred arm",
        "Gain verbal consent",
        "Check for relevant allergies (e.g. latex, antiseptic)",
        "Select the appropriate blood bottles and needle/vacutainer for the tests required",
        "Gather equipment: gloves, tourniquet, alcohol wipe, gauze/cotton wool, tape, sample bottles",
        "Take a sharps bin to the bedside",
        "Decontaminate hands and put on gloves",
        "Apply the tourniquet a few centimetres proximal to the intended site and select a suitable vein",
        "Clean the site with an alcohol wipe and allow it to dry for 30 seconds",
        "Do not re-palpate the cleaned site",
        "Anchor the vein by stretching the skin distally with your non-dominant hand",
        "Insert the needle bevel-up at roughly 15-30 degrees to the skin",
        "Collect blood into the appropriate bottles in the correct order of draw",
        "Release the tourniquet before withdrawing the needle",
        "Withdraw the needle and immediately apply pressure with gauze",
        "Dispose of the needle directly into the sharps bin",
        "Apply pressure for 30-60 seconds (or until bleeding stops); apply tape/dressing",
        "Label the bottles at the bedside with the patient's details",
        "Dispose of waste; remove gloves and decontaminate hands",
        "Thank the patient and ensure they are comfortable",
        "Document the procedure as required",
    ],

    "Phlebotomy & Vascular :: Peripheral IV Cannulation": [
        "Wash hands / apply alcohol gel and put on apron",
        "Introduce yourself by name and role",
        "Confirm patient identity (name, date of birth, and ID number or address)",
        "Explain the procedure and gain verbal consent; warn of a sharp scratch",
        "Check for relevant allergies",
        "Consider whether local anaesthetic is appropriate",
        "Select an appropriately sized cannula for the indication",
        "Gather equipment: gloves, tourniquet, alcohol wipe, cannula, extension set/cap, saline flush, dressing, gauze",
        "Check expiry dates on all packaging",
        "Take a sharps bin to the bedside",
        "Decontaminate hands and put on gloves",
        "Apply the tourniquet and select a suitable vein",
        "Clean the site with an alcohol wipe and allow it to dry for 30 seconds",
        "Anchor the vein by stretching the skin distally",
        "Ensure the bevel is uppermost; insert at roughly 10-30 degrees to the skin",
        "Advance until the first flashback is seen in the chamber",
        "Lower the angle and advance a further 1-2 mm",
        "Fix the needle and advance the cannula off the needle into the vein",
        "Release the tourniquet",
        "Occlude the vein proximal to the cannula tip and withdraw the needle fully",
        "Dispose of the needle immediately into the sharps bin",
        "Attach the cap/extension set and apply a sterile dressing",
        "Flush with 0.9% sodium chloride to confirm patency (stop if resistance, pain, or swelling)",
        "Dispose of waste; remove gloves and decontaminate hands",
        "Document: date, indication, site, cannula size, and number of attempts",
    ],

    "Phlebotomy & Vascular :: Paediatric Cannulation": [
        "Wash hands; introduce yourself to the child and carer",
        "Confirm the child's identity and check the weight/age-appropriate plan",
        "Explain in age-appropriate terms; gain consent from the carer (and assent from the child)",
        "Consider topical local anaesthetic cream applied in advance, and distraction/play support",
        "Check for allergies",
        "Select a small, appropriately sized cannula and gather equipment",
        "Ensure a trained assistant is available for safe, gentle immobilisation",
        "Decontaminate hands and put on gloves",
        "Apply a tourniquet (or assistant's hand) and select a vein (hand, foot, or antecubital)",
        "Clean the site and allow to dry",
        "Insert the cannula bevel-up at a shallow angle; watch for flashback",
        "Advance the cannula off the needle; release the tourniquet",
        "Withdraw the needle into the sharps bin immediately",
        "Attach and flush gently to confirm patency",
        "Secure well with a dressing appropriate for children; consider a splint",
        "Comfort the child; dispose of waste; remove gloves and wash hands",
        "Document the procedure",
    ],

    "Phlebotomy & Vascular :: Arterial Blood Gas (ABG)": [
        "Gather equipment: pre-heparinised ABG syringe, alcohol wipe, gauze, gloves, sharps bin",
        "Consider topical local anaesthetic",
        "Introduce yourself and confirm patient identity",
        "Explain the procedure and gain verbal consent",
        "Decontaminate hands and put on gloves",
        "Position and support the wrist in slight extension (for radial sampling)",
        "Perform a modified Allen's test to confirm collateral circulation",
        "Palpate and locate the artery with two fingers",
        "Clean the site with an alcohol wipe and allow it to dry for 30 seconds",
        "Set the syringe plunger to the recommended sample volume if required",
        "Warn of a sharp scratch; insert the needle bevel-up at roughly 45 degrees toward the pulse",
        "Allow the syringe to fill with pulsatile arterial blood",
        "Withdraw the needle and apply firm pressure for at least 5 minutes",
        "Safely remove/cap the needle into the sharps bin",
        "Expel any air bubbles and cap the syringe; mix gently",
        "Remove gloves and decontaminate hands",
        "Label the sample at the bedside; analyse promptly (on ice if delay expected)",
        "Document the procedure",
    ],

    "Phlebotomy & Vascular :: Blood Cultures": [
        "Introduce yourself and confirm patient identity",
        "Explain the procedure and gain verbal consent",
        "Decontaminate hands; clean a tray/trolley and assemble equipment",
        "Gather: culture bottles, needle/winged set, alcohol wipes, chlorhexidine/alcohol skin prep, gloves, tourniquet, sharps bin",
        "Decontaminate hands and put on apron and gloves",
        "Remove bottle caps and disinfect the bottle tops; allow to air dry",
        "Apply the tourniquet and select a suitable vein",
        "Clean the skin with 2% chlorhexidine in 70% alcohol over a wide area; allow to dry",
        "Do not re-palpate the cleaned site (no-touch technique)",
        "Insert the needle bevel-up at roughly 15 degrees to the skin",
        "Inoculate the aerobic bottle first, then the anaerobic bottle, with the recommended volume",
        "Release the tourniquet before withdrawing the needle",
        "Withdraw the needle and apply pressure with gauze",
        "Dispose of sharps immediately into the sharps bin",
        "Label bottles at the bedside; place in a sealed bag",
        "Remove gloves/apron and decontaminate hands",
        "Document the procedure and send to the lab promptly",
    ],

    "Phlebotomy & Vascular :: IV Fluid Set-up & Administration": [
        "Wash hands; confirm patient identity and check the fluid prescription",
        "Confirm the correct fluid type, volume, additives, and rate against the chart",
        "Check for allergies; explain to the patient and gain consent",
        "Gather: prescribed fluid bag, giving set, gloves; check the bag for clarity and expiry",
        "Decontaminate hands and put on gloves",
        "Close the roller clamp on the giving set",
        "Spike the fluid bag using aseptic technique and hang it on a drip stand",
        "Squeeze the drip chamber to half-fill it, then open the clamp to prime the line (no air)",
        "Close the clamp once primed",
        "Confirm cannula patency with a saline flush",
        "Connect the primed line to the cannula using a clean technique",
        "Set the infusion rate (by drip count or infusion pump) per the prescription",
        "Label the line/bag and document start time, fluid, and rate",
        "Monitor the patient and the infusion site; remove gloves and wash hands",
    ],

    "Phlebotomy & Vascular :: Central Venous Line Insertion": [
        "NOTE: specialist procedure — confirm against your local protocol and supervision requirements",
        "Confirm indication, check coagulation/platelets, and obtain informed consent",
        "Wash hands; gather a central line pack, ultrasound, sterile gown/gloves, drapes, local anaesthetic, flush",
        "Position the patient appropriately (e.g. Trendelenburg for internal jugular) and confirm site",
        "Apply full barrier precautions: cap, mask, sterile gown and gloves",
        "Use ultrasound to identify the vein; clean the skin with chlorhexidine and drape widely",
        "Infiltrate local anaesthetic at the planned puncture site",
        "Under ultrasound guidance, puncture the vein and confirm venous blood (not pulsatile/bright)",
        "Pass the guidewire through the needle (Seldinger technique), watching for arrhythmia",
        "Remove the needle, keeping hold of the wire at all times",
        "Make a small skin nick and pass the dilator over the wire, then remove the dilator",
        "Railroad the catheter over the wire to the predetermined depth",
        "Remove the guidewire; aspirate and flush each lumen, then cap",
        "Secure/suture the line and apply a sterile dressing",
        "Confirm tip position and exclude pneumothorax (e.g. chest X-ray) before use as indicated",
        "Dispose of sharps and waste; document the procedure fully",
    ],

    # ─────────────────────────────────────────────────────────────────────
    # GROUP 3 — Catheters, tubes & drains
    # ─────────────────────────────────────────────────────────────────────

    "Catheters & Tubes :: Urinary Catheterisation (Male)": [
        "Wash hands and gather equipment on a clean trolley",
        "Confirm patient identity and explain the procedure",
        "Gain informed consent and check for allergies (especially latex)",
        "Ensure privacy and assist the patient into a comfortable supine position",
        "Place a protective sheet; adjust lighting; expose only as needed",
        "Put on apron; wash hands; open the catheter pack using aseptic technique",
        "Apply sterile gloves and drape the patient",
        "Retract the foreskin (if present) and clean the glans and meatus with saline, swabbing away from the meatus",
        "Confirm no anaesthetic allergy, then instil local anaesthetic lubricating gel slowly into the urethra",
        "Hold the end of the penis to retain the gel; wait approximately 5 minutes",
        "Remove the outer gloves; position a receiver for urine",
        "Hold the penis upward at about 90 degrees and insert the catheter to the hilt until urine flows",
        "Advance a few more centimetres after urine flows",
        "Inflate the balloon with sterile water per the manufacturer's instructions",
        "Withdraw gently until resistance is felt at the bladder neck",
        "Attach the drainage system and reposition the foreskin over the glans",
        "Collect a sample if required; ensure the patient is comfortable",
        "Dispose of equipment; wash hands",
        "Document: indication, catheter type/size, balloon volume, gel used, and any problems",
    ],

    "Catheters & Tubes :: Urinary Catheterisation (Female)": [
        "Wash hands and gather equipment on a clean trolley",
        "Confirm patient identity and explain the procedure",
        "Gain informed consent and check for allergies (especially latex)",
        "Ensure privacy and assist the patient into a comfortable position",
        "Place a protective sheet; adjust lighting; expose only as needed",
        "Put on apron; wash hands; open the catheter pack using aseptic technique",
        "Apply sterile gloves and drape the patient",
        "Clean the vulval area with saline, swabbing from front to back",
        "Identify the urethral meatus",
        "Instil local anaesthetic lubricating gel into the urethra",
        "Wait approximately 5 minutes; remove the outer gloves",
        "Position a receiver for urine",
        "Insert the catheter into the meatus about 6-8 cm until urine flows",
        "Advance a few more centimetres after urine flows",
        "Inflate the balloon with sterile water per the manufacturer's instructions",
        "Withdraw gently until resistance is felt; attach the drainage system",
        "Collect a sample if required; ensure the patient is comfortable",
        "Dispose of equipment; wash hands",
        "Document: indication, catheter type/size, balloon volume, gel used, and any problems",
    ],

    "Catheters & Tubes :: Nasogastric Tube Insertion": [
        "Introduce yourself and confirm patient identity",
        "Explain the procedure and gain verbal consent",
        "Gather: apron, gloves, NG tube, drainage bag, glass of water, gauze, lubricating gel, 50 ml syringe, pH strips, tape",
        "Decontaminate hands and put on apron and gloves",
        "Sit the patient upright with the head slightly forward",
        "Estimate the length needed: nose to earlobe to xiphisternum; note the marker",
        "Explain the patient will be asked to swallow to help passage",
        "Lubricate the tube and insert into a patent nostril",
        "Advance toward the occiput; ask the patient to swallow (sips of water may help)",
        "Continue advancing during swallowing until the measured mark is reached",
        "Aspirate gastric contents and check pH (5.5 or below on indicator paper as first-line confirmation)",
        "If position is uncertain, confirm with chest X-ray before use",
        "Secure the tube and attach the drainage bag if indicated",
        "Ensure the patient is comfortable; dispose of waste",
        "Decontaminate hands and document the procedure",
    ],

    "Catheters & Tubes :: Intercostal Chest Drain (Seldinger)": [
        "NOTE: specialist procedure — confirm against your local protocol and supervision",
        "Confirm indication and side; review imaging; check coagulation",
        "Obtain informed consent; wash hands; gather a chest drain pack and underwater seal",
        "Position the patient (e.g. arm behind head) and identify the safe triangle",
        "Apply sterile gown and gloves; clean the skin with chlorhexidine and drape",
        "Infiltrate local anaesthetic down to the pleura, aspirating for air/fluid to confirm the space",
        "Make a small skin incision over the upper border of the rib (avoiding the neurovascular bundle)",
        "Insert the introducer needle just above the rib; confirm aspiration of air/fluid",
        "Pass the guidewire, then remove the needle keeping hold of the wire",
        "Dilate the track over the wire",
        "Railroad the drain over the wire to the required depth; remove the wire",
        "Connect to the underwater seal; look for swinging/bubbling",
        "Secure the drain with a suture and apply an occlusive dressing",
        "Confirm position with a chest X-ray",
        "Dispose of sharps/waste; document the procedure and ongoing drain observations",
    ],

    # ─────────────────────────────────────────────────────────────────────
    # GROUP 4 — Airway & respiratory
    # ─────────────────────────────────────────────────────────────────────

    "Airway & Respiratory :: Oxygen Therapy Set-up": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Confirm the oxygen prescription and target saturation range",
        "Assess the patient and measure baseline oxygen saturations",
        "Select the appropriate delivery device for the required flow (nasal cannula, simple mask, or non-rebreathe / Venturi)",
        "Connect the device to the oxygen source and set the prescribed flow rate",
        "For a non-rebreathe mask, pre-fill the reservoir bag before applying",
        "Apply the device comfortably to the patient and ensure a good fit",
        "Re-check saturations and titrate flow to the target range",
        "Document the device, flow rate, and saturations; reassess regularly",
        "Wash hands",
    ],

    "Airway & Respiratory :: Asthma Reliever via Spacer": [
        "Wash hands; confirm patient identity and explain the technique",
        "Check the inhaler and spacer are correct and in date",
        "Remove the inhaler cap and shake the inhaler",
        "Insert the inhaler into the spacer",
        "Ask the patient to exhale gently, then seal their lips around the mouthpiece",
        "Press the inhaler once to release a single dose into the spacer",
        "Ask the patient to take a slow deep breath in (or tidal breathe 5 times if using that method)",
        "Ask them to hold their breath for about 10 seconds if able",
        "Wait about 30 seconds before repeating for a second dose if prescribed",
        "Advise rinsing the mouth if a steroid inhaler was used",
        "Check the patient's technique and document; wash hands",
    ],

    "Airway & Respiratory :: Nebuliser Set-up": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Confirm the prescribed drug, dose, and driving gas (air or oxygen)",
        "Check for allergies; assemble the nebuliser chamber, mask/mouthpiece, and tubing",
        "Draw up or add the prescribed drug into the nebuliser chamber",
        "Connect the chamber to the correct driving gas at the recommended flow (typically 6-8 L/min)",
        "Confirm the chamber is misting",
        "Apply the mask/mouthpiece to the patient and ensure comfort",
        "Allow the nebuliser to run until the chamber is empty",
        "Reassess the patient (and saturations) after the treatment",
        "Dispose of/clean equipment per policy; document the administration; wash hands",
    ],

    "Airway & Respiratory :: Spirometry": [
        "Wash hands; confirm patient identity and explain the test",
        "Check for contraindications (e.g. recent MI, pneumothorax, recent eye/abdominal surgery)",
        "Enter the patient's age, height, sex, and ethnicity for predicted values",
        "Attach a clean disposable mouthpiece/filter",
        "Ask the patient to sit upright and apply a nose clip",
        "Demonstrate: full inhalation, tight lip seal, then blast out as hard and fast as possible",
        "Ask the patient to continue exhaling for at least 6 seconds",
        "Coach actively throughout the manoeuvre",
        "Repeat to obtain at least three acceptable and two reproducible efforts",
        "Record the best FEV1 and FVC and calculate the FEV1/FVC ratio",
        "Interpret as obstructive, restrictive, or normal pattern (consider reversibility if indicated)",
        "Document the results; wash hands",
    ],

    "Airway & Respiratory :: Bag-Mask Ventilation": [
        "Confirm the need for assisted ventilation and call for help",
        "Wash hands / apply gloves; position yourself at the head of the bed",
        "Open the airway with a head-tilt chin-lift (or jaw thrust if C-spine concern)",
        "Consider an oropharyngeal or nasopharyngeal airway adjunct",
        "Select an appropriately sized mask covering the nose and mouth",
        "Connect the bag-valve-mask to high-flow oxygen with a reservoir",
        "Apply the mask using an E-C grip (one or two-person technique)",
        "Achieve a good seal and squeeze the bag to deliver a breath over ~1 second",
        "Watch for chest rise with each breath; ventilate at the appropriate rate",
        "Avoid excessive volume or rate (risk of gastric inflation)",
        "Reassess effectiveness (chest rise, saturations, colour) continuously",
        "Document and escalate as needed",
    ],

    "Airway & Respiratory :: Laryngeal Mask Airway (LMA) Insertion": [
        "NOTE: airway skill — perform only with appropriate training and supervision",
        "Confirm indication; ensure monitoring, oxygen, and suction are available",
        "Wash hands and put on gloves; select the correct LMA size for the patient's weight",
        "Check the cuff for leaks, then fully deflate it and lubricate the posterior surface",
        "Ensure adequate depth of anaesthesia/unconsciousness",
        "Position the head in the sniffing position (if no C-spine concern)",
        "Hold the LMA like a pen; insert along the hard palate with the index finger guiding",
        "Advance until resistance is felt as the tip seats in the hypopharynx",
        "Inflate the cuff to the recommended volume (the device may rise slightly)",
        "Connect to the breathing circuit and confirm ventilation (chest rise, capnography, no major leak)",
        "Secure the device and insert a bite block if appropriate",
        "Monitor continuously; document the size used and ease of insertion",
    ],

    "Airway & Respiratory :: Pre-oxygenation at Induction": [
        "Confirm the plan for induction and that all equipment and help are ready",
        "Wash hands; ensure monitoring is attached (SpO2, ECG, BP, capnography)",
        "Explain to the patient (if awake) and position appropriately (sniffing/ramped)",
        "Select a well-fitting facemask connected to high-flow oxygen",
        "Apply the mask to achieve a tight seal with no leak",
        "Deliver high FiO2 and ask the patient to breathe normally for ~3 minutes (or 8 vital-capacity breaths)",
        "Aim for an end-tidal oxygen target where monitored",
        "Maintain the seal until the airway is secured",
        "Be prepared with suction and airway adjuncts/rescue devices",
        "Document pre-oxygenation as part of the anaesthetic record",
    ],

    # ─────────────────────────────────────────────────────────────────────
    # GROUP 5 — Cardiac, ophthalmology, ENT & measurement
    # ─────────────────────────────────────────────────────────────────────

    "Cardiac & Monitoring :: 12-Lead ECG": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent and ensure privacy; expose the chest, wrists, and ankles",
        "Ask about and address skin preparation (clip hair if needed, clean/dry skin)",
        "Attach limb electrodes: red right arm, yellow left arm, green left leg, black right leg",
        "Place V1 in the 4th intercostal space at the right sternal edge",
        "Place V2 in the 4th intercostal space at the left sternal edge",
        "Place V4 in the 5th intercostal space at the mid-clavicular line",
        "Place V3 midway between V2 and V4",
        "Place V5 at the left anterior axillary line, level with V4",
        "Place V6 at the left mid-axillary line, level with V4 and V5",
        "Ask the patient to relax and keep still; check the trace quality",
        "Record the ECG; enter patient details and the date/time",
        "Remove electrodes; ensure the patient is comfortable; wash hands",
        "Interpret systematically (rate, rhythm, axis, intervals, ST/T changes) and act on findings",
    ],

    "Ophthalmology :: Fundoscopy": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent; dim the room lights; consider mydriatic drops if appropriate",
        "Check the ophthalmoscope is working and set the dial to zero (or your refractive correction)",
        "Ask the patient to fixate on a distant target and keep still",
        "Use your right eye/right hand for the patient's right eye, and vice versa",
        "Locate the red reflex from about an arm's length",
        "Move in toward the eye, following the red reflex",
        "Identify the optic disc (colour, contour, cup) by following vessels back to it",
        "Examine the four vascular arcades for the retinal vessels",
        "Inspect the macula by asking the patient to look directly at the light briefly",
        "Repeat for the other eye",
        "Wash hands; document the findings",
    ],

    "Ophthalmology :: Slit Lamp Examination": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent; adjust the seat, table, and chin/forehead rest for the patient",
        "Ask the patient to place their chin on the rest and forehead against the bar",
        "Align the eyes with the marker on the frame",
        "Set a moderate magnification and a medium beam width to begin",
        "Systematically examine the lids, lashes, conjunctiva, and sclera",
        "Examine the cornea (consider fluorescein for epithelial defects)",
        "Examine the anterior chamber (depth, cells/flare) using a narrow beam",
        "Examine the iris and lens",
        "Adjust the beam and magnification as needed for detail",
        "Examine the other eye",
        "Clean the chin/forehead rest; wash hands; document findings",
    ],

    "Ophthalmology :: Fluorescein Instillation & Interpretation": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent and check for relevant allergies",
        "Ask about contact lenses and remove them if present",
        "Moisten a fluorescein strip with sterile saline (or use a drop preparation)",
        "Ask the patient to look up and gently touch the strip to the lower conjunctival fornix",
        "Ask the patient to blink to distribute the dye",
        "Examine under a cobalt blue light (slit lamp or blue light)",
        "Look for areas of green uptake indicating epithelial defects/abrasions",
        "Note any dendritic pattern (suggesting herpetic keratitis)",
        "Document the findings and act accordingly",
        "Wash hands",
    ],

    "ENT :: Otoscopy": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent; select a clean, appropriately sized speculum",
        "Inspect the pinna and external auditory meatus first",
        "Hold the otoscope like a pen, bracing against the cheek to avoid injury",
        "Gently pull the pinna up and back (in adults) to straighten the canal",
        "Insert the speculum under direct vision; examine the canal walls",
        "Identify the tympanic membrane, light reflex, handle of malleus, and pars tensa",
        "Note colour, contour, perforation, fluid, or discharge",
        "Repeat on the other ear (examine the normal/less affected ear first)",
        "Dispose of the speculum; wash hands; document findings",
    ],

    "ENT :: External Auditory Canal Procedure (Ear Toilet / Microsuction)": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent and explain that there may be loud noise (with microsuction)",
        "Examine the ear with otoscopy/microscope to assess the canal and drum",
        "Select the appropriate method (dry mopping, microsuction, or syringing per policy)",
        "Position the patient and stabilise the head",
        "Under direct vision, gently remove wax/debris, avoiding the canal walls and drum",
        "Pause if the patient reports pain or dizziness",
        "Re-examine the canal and tympanic membrane after clearing",
        "Advise the patient on aftercare",
        "Dispose of/clean equipment; wash hands; document findings",
    ],

    "Measurement :: Plot Infant/Child Growth & BMI": [
        "Wash hands; confirm the child's identity and explain to the carer",
        "Gain consent; use age-appropriate, calibrated equipment",
        "Measure weight with minimal clothing on a calibrated scale",
        "Measure length (lying, under 2 years) or height (standing, over 2 years) correctly",
        "Measure head circumference at the widest point where indicated",
        "Use the correct growth chart for age and sex (and corrected age if premature)",
        "Plot each measurement accurately on the appropriate centile chart",
        "Calculate BMI where appropriate and plot on the BMI centile chart",
        "Interpret the centiles and any crossing of centile lines over time",
        "Discuss findings with the carer; document and act on concerns",
        "Wash hands",
    ],

    # ─────────────────────────────────────────────────────────────────────
    # GROUP 6 — Wound care, suturing & surgical basics
    # ─────────────────────────────────────────────────────────────────────

    "Surgical Skills :: Scrub for Sterile Procedure": [
        "Remove all hand/wrist jewellery; ensure nails are short and clean; roll sleeves up",
        "Put on a surgical cap and mask",
        "Open the gown and glove packs onto a sterile surface without contaminating them",
        "Turn on the tap and wet hands and forearms to the elbows",
        "Perform a surgical hand wash, washing from fingertips to elbows (keep hands highest)",
        "Use a nail brush/pick for the nails as per local policy on the first scrub",
        "Rinse from fingertips to elbows, keeping hands above the elbows throughout",
        "Dry each hand and arm with a separate sterile towel, fingertips to elbow",
        "Apply surgical hand antisepsis if using an alcohol rub method",
        "Don the sterile gown without touching the outside",
        "Apply sterile gloves using a closed (or open) gloving technique",
        "Keep hands above the waist and within the sterile field at all times",
    ],

    "Surgical Skills :: Basic Interrupted Suturing": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent; check for allergies (including local anaesthetic)",
        "Assess the wound; ensure it is clean and haemostasis is achieved",
        "Set up a sterile field and equipment (needle holder, forceps, suture, scissors)",
        "Put on sterile gloves",
        "Infiltrate local anaesthetic and confirm adequate anaesthesia",
        "Mount the needle in the needle holder about two-thirds from the tip",
        "Evert the wound edge with forceps and enter the skin at 90 degrees",
        "Pass the needle through, taking equal bites of each side at equal depth",
        "Tie a secure surgical knot (instrument tie), laying flat, not too tight",
        "Position the knot to one side of the wound, off the incision line",
        "Place sufficient evenly spaced interrupted sutures to close the wound",
        "Clean the wound and apply a dressing",
        "Dispose of sharps safely; give wound care and suture-removal advice",
        "Document the procedure and anaesthetic used",
    ],

    "Surgical Skills :: Complex Wound Suturing": [
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Assess the wound fully (depth, structures involved, contamination, tension)",
        "Ensure adequate analgesia/anaesthesia and haemostasis",
        "Set up a sterile field; consider whether layered closure is required",
        "Debride and irrigate as needed; explore for foreign bodies or deep injury",
        "Close deep/dead space with absorbable buried sutures to reduce tension",
        "Approximate the deeper layers anatomically",
        "Close the skin with appropriate technique (e.g. interrupted, mattress for high tension)",
        "Ensure edges are everted and well aligned, especially at landmarks",
        "Clean and dress the wound",
        "Dispose of sharps; advise on wound care, follow-up, and suture removal",
        "Consider tetanus status and antibiotics if indicated",
        "Document the injury, repair, and aftercare plan",
    ],

    "Surgical Skills :: Paediatric Wound Closure": [
        "Wash hands; introduce yourself to the child and carer; explain age-appropriately",
        "Gain consent from the carer (assent from the child); check allergies",
        "Use distraction/play and consider topical anaesthetic where suitable",
        "Assess the wound and decide on the least distressing effective method",
        "For suitable small wounds, consider tissue adhesive or adhesive strips",
        "Clean and irrigate the wound; ensure haemostasis",
        "Apply the chosen closure (adhesive, strips, or sutures) with gentle technique",
        "If suturing, ensure adequate anaesthesia and minimal handling",
        "Comfort the child throughout; involve the carer",
        "Dress the wound appropriately for a child",
        "Advise on aftercare, follow-up, and tetanus status",
        "Document the procedure",
    ],

    "Surgical Skills :: Perineal Suturing": [
        "NOTE: obstetric skill — perform with appropriate training and supervision",
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Ensure good lighting, positioning, and analgesia (top-up regional or infiltrate local)",
        "Assess the degree of perineal trauma and identify the apex of the tear",
        "Set up a sterile field; perform a swab and instrument count with an assistant",
        "Confirm haemostasis and identify anatomy (consider rectal examination to exclude OASI)",
        "Suture the vaginal wall with a continuous technique, starting above the apex",
        "Re-appose the perineal muscles",
        "Close the perineal skin (e.g. subcuticular continuous suture)",
        "Perform a final rectal examination to ensure no suture has breached the rectum",
        "Repeat the swab and instrument count with the assistant",
        "Document the degree of tear, repair, counts, and aftercare advice",
    ],

    "Surgical Skills :: Suture or Wound Staple Removal": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Gain consent; confirm the wound has healed enough for removal",
        "Gather equipment: stitch cutter or staple remover, forceps, gauze, gloves",
        "Put on gloves; clean the wound if needed",
        "For sutures: lift the knot with forceps, cut one side close to the skin, and pull the suture out toward the wound",
        "For staples: position the remover under the staple, squeeze to bend it open, and lift out",
        "Remove alternate sutures/staples first if the wound integrity is uncertain",
        "Inspect the wound for dehiscence or signs of infection",
        "Apply adhesive strips if extra support is needed",
        "Dispose of sharps; remove gloves and wash hands",
        "Advise on aftercare; document the procedure",
    ],

    "Surgical Skills :: Excision / Biopsy of a Skin Lesion": [
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Mark the lesion with appropriate margins and orientation (consider skin tension lines)",
        "Set up a sterile field and equipment; put on sterile gloves",
        "Clean the skin and drape",
        "Infiltrate local anaesthetic and confirm anaesthesia",
        "Incise around the marked ellipse through the dermis",
        "Excise the lesion with the planned margin and appropriate depth",
        "Achieve haemostasis",
        "Place the specimen in fixative; label and complete the request form (note orientation if needed)",
        "Close the defect in layers as required",
        "Clean and dress the wound",
        "Dispose of sharps; advise on aftercare and how results will be given",
        "Document the procedure",
    ],

    "Surgical Skills :: Incision & Drainage of an Abscess": [
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Assess the abscess (site, size, fluctuance, surrounding cellulitis)",
        "Set up a sterile field and equipment; put on sterile gloves",
        "Clean the skin and drape",
        "Infiltrate local anaesthetic around (field block) — note anaesthesia is harder in infected tissue",
        "Make an incision over the point of maximal fluctuance",
        "Allow pus to drain; send a sample for culture",
        "Break down loculations with a gloved finger or instrument",
        "Irrigate the cavity",
        "Pack the cavity if indicated (or leave open to heal by secondary intention)",
        "Apply a dressing",
        "Dispose of sharps; advise on follow-up, packing changes, and safety-netting",
        "Document the procedure",
    ],

    "Surgical Skills :: Debridement of a Contaminated Wound": [
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Assess the wound, neurovascular status, and degree of contamination",
        "Ensure adequate analgesia/anaesthesia",
        "Set up a sterile field; put on sterile gloves",
        "Irrigate copiously with saline to remove gross contamination",
        "Remove foreign material and clearly devitalised/necrotic tissue",
        "Preserve viable tissue and important structures",
        "Re-irrigate and reassess tissue viability",
        "Decide on closure (primary, delayed primary, or secondary) based on contamination",
        "Dress the wound appropriately",
        "Consider tetanus prophylaxis and antibiotics",
        "Dispose of sharps; document the procedure and plan",
    ],

    "Surgical Skills :: Compression Bandage / Stocking Application": [
        "Wash hands; confirm patient identity and explain the procedure",
        "Confirm indication and that arterial supply is adequate (e.g. ABPI checked where required)",
        "Gain consent; position the limb and inspect the skin",
        "Select the correct compression class and size",
        "For bandaging: apply padding, then bandage from the base of the toes upward with even, graduated tension",
        "Maintain consistent overlap and keep the foot at 90 degrees",
        "Avoid wrinkles, gaps, and excessive pressure over bony prominences",
        "For stockings: ensure correct measurement and apply smoothly without rolling the top",
        "Check toes for colour, warmth, and sensation after application",
        "Advise the patient on warning signs and care",
        "Wash hands; document application and skin condition",
    ],

    # ─────────────────────────────────────────────────────────────────────
    # GROUP 7 — Orthopaedics & MSK
    # ─────────────────────────────────────────────────────────────────────

    "Orthopaedics :: Plaster/Cast Application — Upper Limb": [
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Confirm the injury, imaging, and the position the limb should be held in",
        "Assess and document distal neurovascular status before starting",
        "Gather: stockinette, wool padding, plaster/synthetic casting material, water, gloves",
        "Apply stockinette smoothly over the limb",
        "Apply wool padding evenly with overlap, extra over bony prominences",
        "Wet the casting material and apply, smoothing in the desired position",
        "Maintain the correct position of immobilisation until set (do not indent with fingertips)",
        "Mould and ensure joints are immobilised as intended while leaving others free",
        "Check the cast is not too tight; trim edges and ensure comfort",
        "Re-check and document distal neurovascular status after application",
        "Give cast-care advice and red-flag warnings (pain, numbness, swelling)",
        "Arrange follow-up; wash hands; document",
    ],

    "Orthopaedics :: Plaster/Cast Application — Lower Limb": [
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Confirm the injury, imaging, and required position of immobilisation",
        "Assess and document distal neurovascular status before starting",
        "Gather: stockinette, wool padding, casting material, water, gloves",
        "Apply stockinette smoothly over the limb",
        "Apply wool padding evenly, with extra over the malleoli and heel",
        "Wet and apply the casting material, holding the ankle/limb in the correct position",
        "Hold the position until the cast sets (avoid fingertip indentation)",
        "Mould appropriately and ensure the intended joints are immobilised",
        "Check the cast is not constricting; trim and finish the edges",
        "Re-check and document distal neurovascular status after application",
        "Advise on weight-bearing status, cast care, and red flags",
        "Arrange follow-up; wash hands; document",
    ],

    "Orthopaedics :: Joint Aspiration / Injection": [
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Confirm the indication and review relevant imaging/anatomy",
        "Set up a sterile field and equipment; put on sterile gloves",
        "Identify and mark the correct landmarks for the joint",
        "Clean the skin with antiseptic and drape",
        "Infiltrate local anaesthetic if required",
        "Insert the needle into the joint space using a no-touch technique",
        "Aspirate fluid (send for microscopy, culture, and crystals if indicated)",
        "If injecting, confirm placement, then change syringe and inject the agent smoothly",
        "Withdraw the needle and apply a dressing",
        "Dispose of sharps; advise on aftercare and possible post-injection flare",
        "Document the procedure and any samples sent",
    ],

    "Orthopaedics :: Joint Relocation / Fracture Reduction": [
        "NOTE: perform with appropriate analgesia/sedation, monitoring, and supervision",
        "Confirm identity, injury, and imaging; assess and document neurovascular status",
        "Explain the procedure and gain consent; check allergies",
        "Ensure adequate analgesia/sedation with appropriate monitoring and help",
        "Position the patient and limb appropriately",
        "Apply the reduction manoeuvre specific to the injury, with controlled traction",
        "Aim for smooth, sustained force rather than sudden movements",
        "Confirm clinical reduction (alignment, range, reduced deformity)",
        "Immobilise with a backslab/splint or sling as appropriate",
        "Re-assess and document neurovascular status after reduction",
        "Confirm position with post-reduction imaging",
        "Document the procedure, sedation, and neurovascular checks",
    ],

    "Orthopaedics :: Orthopaedic Theatre Attendance (Implant/Joint)": [
        "Confirm you are expected and have completed any pre-theatre requirements",
        "Perform a surgical scrub if scrubbing in (otherwise observe from outside the sterile field)",
        "Participate in the WHO surgical safety checklist / team brief",
        "Maintain sterility: keep within/away from the sterile field as appropriate",
        "Observe patient positioning, prepping, and draping",
        "Follow the operative steps (e.g. exposure, reduction, implant placement)",
        "Understand the implants/instruments used and their purpose",
        "Observe closure and dressing",
        "Participate in the team debrief and swab/instrument count awareness",
        "Reflect on indications, complications, and post-op plan; document attendance for your portfolio",
    ],

    "Orthopaedics :: Digital Nerve Block": [
        "Wash hands; confirm identity, explain, and gain consent; check allergies",
        "Assess and document distal neurovascular status and sensation",
        "Confirm appropriate local anaesthetic WITHOUT adrenaline for digits (per local policy)",
        "Set up a sterile field; put on gloves",
        "Clean the skin at the base of the digit",
        "Insert the needle at one side of the base of the proximal phalanx",
        "Aspirate to avoid intravascular injection, then inject anaesthetic to block the digital nerve",
        "Repeat on the other side of the digit",
        "Allow time for the block to take effect; confirm anaesthesia before proceeding",
        "Re-check perfusion of the digit",
        "Dispose of sharps; document the block and neurovascular checks",
    ],

    # ─────────────────────────────────────────────────────────────────────
    # GROUP 8 — Neurology, gynaecology & obstetrics
    # ─────────────────────────────────────────────────────────────────────

    "Neurology :: Lumbar Puncture": [
        "NOTE: confirm no contraindication (e.g. raised ICP/focal signs needing imaging first, coagulopathy)",
        "Confirm identity, explain, and gain informed consent; check allergies and coagulation",
        "Wash hands; gather an LP pack, manometer, sample bottles, local anaesthetic, antiseptic",
        "Position the patient in the left lateral position with knees drawn up (or sitting)",
        "Identify the L3/4 or L4/5 space (around the intercristal line)",
        "Apply sterile gloves (and gown); clean the skin widely and drape",
        "Infiltrate local anaesthetic at the chosen space",
        "Insert the spinal needle in the midline, angled slightly toward the umbilicus, bevel aligned",
        "Advance until a give is felt; remove the stylet to check for CSF flow",
        "Measure the opening pressure with the manometer if indicated",
        "Collect CSF into the numbered bottles in order (plus glucose, with paired serum glucose)",
        "Reinsert the stylet before withdrawing the needle",
        "Apply a dressing; advise the patient on post-LP care",
        "Dispose of sharps; label samples; document the procedure and opening pressure",
    ],

    "Gynaecology :: Female Speculum Examination": [
        "Wash hands; confirm identity, explain, and gain consent; offer a chaperone and document",
        "Ensure privacy, dignity, and a warm, lubricated speculum of appropriate size",
        "Ask the patient to empty her bladder beforehand if relevant",
        "Position the patient appropriately and expose only when ready",
        "Put on gloves; inspect the external genitalia",
        "Warn the patient, then gently insert the speculum in the correct orientation",
        "Open the blades to visualise the cervix",
        "Inspect the cervix and vaginal walls",
        "Take samples (e.g. swabs or smear) if indicated using the correct technique",
        "Close and withdraw the speculum gently",
        "Allow the patient to redress; ensure comfort",
        "Dispose of equipment; remove gloves and wash hands; document findings and chaperone",
    ],

    "Gynaecology :: Colposcopy": [
        "NOTE: specialist procedure — performed with appropriate training",
        "Confirm identity, explain, and gain informed consent; offer a chaperone",
        "Review the referral (e.g. smear result) and history; check allergies",
        "Position the patient and insert a speculum to visualise the cervix",
        "Inspect the cervix under magnification with the colposcope",
        "Apply acetic acid and observe for acetowhite changes",
        "Apply iodine (Lugol's) and note non-staining areas if used",
        "Identify the transformation zone and any abnormal areas",
        "Take a biopsy of suspicious areas if indicated",
        "Achieve haemostasis (e.g. silver nitrate / Monsel's solution) as needed",
        "Remove the speculum; allow the patient to redress",
        "Explain findings and follow-up; document the procedure and samples",
    ],

    "Gynaecology :: Insertion of Intrauterine Device (IUCD)": [
        "NOTE: specialist procedure — performed with appropriate training",
        "Confirm identity, explain, and gain informed consent; offer a chaperone",
        "Exclude pregnancy and check for contraindications; check allergies",
        "Perform a bimanual examination to assess uterine size and position",
        "Insert a speculum and clean the cervix with antiseptic",
        "Apply a tenaculum to stabilise the cervix if needed",
        "Sound the uterus to measure depth and confirm direction",
        "Load and insert the IUCD per the device instructions to the fundus",
        "Release the device and withdraw the inserter",
        "Trim the threads to an appropriate length",
        "Remove instruments; allow the patient to recover",
        "Advise on aftercare, thread-checking, and warning signs; document the device and batch",
    ],

    "Obstetrics :: Vaginal Delivery (Conduct & Log)": [
        "NOTE: conducted under midwifery/obstetric supervision; this is a structured overview",
        "Confirm consent and ensure the birth environment and equipment are ready",
        "Wash hands; apply apron, gloves, and eye protection",
        "Monitor maternal and fetal wellbeing throughout the second stage",
        "Encourage effective pushing with contractions",
        "Support the perineum and control the speed of the head as it crowns",
        "Check for the cord around the neck once the head delivers",
        "Allow restitution, then deliver the anterior then posterior shoulder with gentle traction",
        "Deliver the body and note the time of birth",
        "Dry and assess the baby; delayed cord clamping if appropriate; skin-to-skin",
        "Manage the third stage (active or physiological) and check the placenta is complete",
        "Inspect for perineal trauma and estimate blood loss",
        "Document the delivery, timings, and any complications in the birth log",
    ],
}
