# ═══════════════════════════════════════════════════════════════════════════
# procedures.py — Procedural skills checklists for The Differential
#
# These checklists are written in ORIGINAL wording from standard clinical
# practice (the steps are how the procedures are correctly performed; no
# checklist has been copied verbatim from any commercial or institutional
# source). Safe to keep in a public repo.
#
# HOW TO ADD A PROCEDURE:
#   "Category :: Procedure Name": [
#       "Step one text",
#       "Step two text",
#       ...
#   ],
# Use the same "Category :: Name" convention as the rest of the app so the
# category filter groups them. Keep each step a single clear action.
# ═══════════════════════════════════════════════════════════════════════════

BUILTIN_PROCEDURES = {

    "Phlebotomy & Vascular :: Venepuncture": [
        "Wash hands / apply alcohol gel and put on apron",
        "Introduce yourself by name and role",
        "Confirm patient identity (name, date of birth, and ID number or address)",
        "Explain the procedure and what it involves; ask about a preferred arm",
        "Gain verbal consent",
        "Check for relevant allergies (e.g. latex, antiseptic)",
        "Select the appropriate blood bottles and needle/vacutainer for the tests required",
        "Gather equipment: gloves, tourniquet, alcohol wipe, gauze/cotton wool, tape, sample bottles",
        "Take a sharps bin to the bedside",
        "Decontaminate hands and put on gloves",
        "Apply the tourniquet a few centimetres proximal to the intended site and select a suitable vein",
        "Clean the site with an alcohol wipe and allow it to dry for 30 seconds",
        "Do not re-palpate the cleaned site",
        "Anchor the vein by stretching the skin distally with your non-dominant hand",
        "Insert the needle bevel-up at roughly 15–30° to the skin",
        "Collect blood into the appropriate bottles in the correct order",
        "Release the tourniquet before withdrawing the needle",
        "Withdraw the needle and immediately apply pressure with gauze",
        "Dispose of the needle directly into the sharps bin",
        "Apply pressure for 30–60 seconds (or until bleeding stops); apply tape/dressing",
        "Label the bottles at the bedside with the patient's details",
        "Dispose of waste; remove gloves and decontaminate hands",
        "Thank the patient and ensure they are comfortable",
        "Document the procedure as required",
    ],

    "Phlebotomy & Vascular :: IV Cannulation": [
        "Wash hands / apply alcohol gel and put on apron",
        "Introduce yourself by name and role",
        "Confirm patient identity (name, date of birth, and ID number or address)",
        "Explain the procedure and gain verbal consent; warn of a sharp scratch",
        "Check for relevant allergies",
        "Consider whether local anaesthetic is appropriate",
        "Select an appropriately sized cannula for the indication",
        "Gather equipment: gloves, tourniquet, alcohol wipe, cannula, extension set/cap, saline flush, dressing, gauze",
        "Check expiry dates on all packaging",
        "Take a sharps bin to the bedside",
        "Decontaminate hands and put on gloves",
        "Apply the tourniquet and select a suitable vein",
        "Clean the site with an alcohol wipe and allow it to dry for 30 seconds",
        "Anchor the vein by stretching the skin distally",
        "Ensure the bevel is uppermost; insert at roughly 10–30° to the skin",
        "Advance until the first flashback is seen in the chamber",
        "Lower the angle and advance a further 1–2 mm",
        "Fix the needle and advance the cannula off the needle into the vein",
        "Release the tourniquet",
        "Occlude the vein proximal to the cannula tip and withdraw the needle fully",
        "Dispose of the needle immediately into the sharps bin",
        "Attach the cap/extension set and apply a sterile dressing",
        "Flush with 0.9% sodium chloride to confirm patency (stop if resistance, pain, or swelling)",
        "Dispose of waste; remove gloves and decontaminate hands",
        "Document: date, indication, site, cannula size, and number of attempts",
    ],

    "Phlebotomy & Vascular :: Arterial Blood Gas (ABG)": [
        "Gather equipment: pre-heparinised ABG syringe, alcohol wipe, gauze, gloves, sharps bin",
        "Consider topical local anaesthetic",
        "Introduce yourself and confirm patient identity",
        "Explain the procedure and gain verbal consent",
        "Decontaminate hands and put on gloves",
        "Position and support the wrist in slight extension (for radial sampling)",
        "Perform a modified Allen's test to confirm collateral circulation",
        "Palpate and locate the artery with two fingers",
        "Clean the site with an alcohol wipe and allow it to dry for 30 seconds",
        "Set the syringe plunger to the recommended sample volume if required",
        "Warn of a sharp scratch; insert the needle bevel-up at roughly 45° toward the pulse",
        "Allow the syringe to fill with pulsatile arterial blood",
        "Withdraw the needle and apply firm pressure for at least 5 minutes",
        "Safely remove/cap the needle into the sharps bin",
        "Expel any air bubbles and cap the syringe; mix gently",
        "Remove gloves and decontaminate hands",
        "Label the sample at the bedside; analyse promptly (on ice if delay expected)",
        "Document the procedure",
    ],

    "Phlebotomy & Vascular :: Blood Cultures": [
        "Introduce yourself and confirm patient identity",
        "Explain the procedure and gain verbal consent",
        "Decontaminate hands; clean a tray/trolley and assemble equipment",
        "Gather: culture bottles, needle/winged set, alcohol wipes, chlorhexidine/alcohol skin prep, gloves, tourniquet, sharps bin",
        "Decontaminate hands and put on apron and gloves",
        "Remove bottle caps and disinfect the bottle tops; allow to air dry",
        "Apply the tourniquet and select a suitable vein",
        "Clean the skin with 2% chlorhexidine in 70% alcohol over a wide area; allow to dry",
        "Do not re-palpate the cleaned site (no-touch technique)",
        "Insert the needle bevel-up at roughly 15° to the skin",
        "Inoculate the aerobic bottle first, then the anaerobic bottle, with the recommended volume",
        "Release the tourniquet before withdrawing the needle",
        "Withdraw the needle and apply pressure with gauze",
        "Dispose of sharps immediately into the sharps bin",
        "Label bottles at the bedside; place in a sealed bag",
        "Remove gloves/apron and decontaminate hands",
        "Document the procedure and send to the lab promptly",
    ],

    "Catheters & Tubes :: Urinary Catheterisation (Male)": [
        "Wash hands and gather equipment on a clean trolley",
        "Confirm patient identity and explain the procedure",
        "Gain informed consent and check for allergies (especially latex)",
        "Ensure privacy and assist the patient into a comfortable supine position",
        "Place a protective sheet; adjust lighting; expose only as needed",
        "Put on apron; wash hands; open the catheter pack using aseptic technique",
        "Apply sterile gloves and drape the patient",
        "Retract the foreskin (if present) and clean the glans and meatus with saline, swabbing away from the meatus",
        "Confirm no anaesthetic allergy, then instil local anaesthetic lubricating gel slowly into the urethra",
        "Hold the end of the penis to retain the gel; wait approximately 5 minutes",
        "Remove the outer gloves; position a receiver for urine",
        "Hold the penis upward at about 90° and insert the catheter to the hilt until urine flows",
        "Advance a few more centimetres after urine flows",
        "Inflate the balloon with sterile water per the manufacturer's instructions",
        "Withdraw gently until resistance is felt at the bladder neck",
        "Attach the drainage system and reposition the foreskin over the glans",
        "Collect a sample if required; ensure the patient is comfortable",
        "Dispose of equipment; wash hands",
        "Document: indication, catheter type/size, balloon volume, gel used, and any problems",
    ],

    "Catheters & Tubes :: Urinary Catheterisation (Female)": [
        "Wash hands and gather equipment on a clean trolley",
        "Confirm patient identity and explain the procedure",
        "Gain informed consent and check for allergies (especially latex)",
        "Ensure privacy and assist the patient into a comfortable position",
        "Place a protective sheet; adjust lighting; expose only as needed",
        "Put on apron; wash hands; open the catheter pack using aseptic technique",
        "Apply sterile gloves and drape the patient",
        "Clean the vulval area with saline, swabbing from front to back",
        "Identify the urethral meatus",
        "Instil local anaesthetic lubricating gel into the urethra",
        "Wait approximately 5 minutes; remove the outer gloves",
        "Position a receiver for urine",
        "Insert the catheter into the meatus about 6–8 cm until urine flows",
        "Advance a few more centimetres after urine flows",
        "Inflate the balloon with sterile water per the manufacturer's instructions",
        "Withdraw gently until resistance is felt; attach the drainage system",
        "Collect a sample if required; ensure the patient is comfortable",
        "Dispose of equipment; wash hands",
        "Document: indication, catheter type/size, balloon volume, gel used, and any problems",
    ],

    "Catheters & Tubes :: Nasogastric Tube Insertion": [
        "Introduce yourself and confirm patient identity",
        "Explain the procedure and gain verbal consent",
        "Gather: apron, gloves, NG tube, drainage bag, glass of water, gauze, lubricating gel, 50 ml syringe, pH strips, tape",
        "Decontaminate hands and put on apron and gloves",
        "Sit the patient upright with the head slightly forward",
        "Estimate the length needed: nose to earlobe to xiphisternum; note the marker",
        "Explain the patient will be asked to swallow to help passage",
        "Lubricate the tube and insert into a patent nostril",
        "Advance toward the occiput; ask the patient to swallow (sips of water may help)",
        "Continue advancing during swallowing until the measured mark is reached",
        "Aspirate gastric contents and check pH (≤5.5 on indicator paper as first-line confirmation)",
        "If position is uncertain, confirm with chest X-ray before use",
        "Secure the tube and attach the drainage bag if indicated",
        "Ensure the patient is comfortable; dispose of waste",
        "Decontaminate hands and document the procedure",
    ],
}
