"""
uq_config.py
============
Configuration for the UQ module of The Differential - UQ Critical Care Module
content (Emergency Medicine & Trauma / Anaesthesia & Pain Management /
Intensive Care) plus the Orthopaedic Trauma Framework viva plus the EMED
practice bank organised by Broad Topic - Pathology.

    section  >  topic   (leaf - questions attach here)

Question content lives elsewhere:
  - MCQ banks:  imported_questions.IMPORTED_BANKS
  - EMED banks: emed_questions.EMED_BANKS  (NEW)
  - Viva banks: imported_questions.IMPORTED_VIVA
  - Orthopaedic Trauma Framework viva: builtin_questions.BUILTIN_VIVA
"""

import re

_COURSE = "UQ Critical Care Module"

# ------------------------------------------------------------
# Original UQ Critical Care Module topics (unchanged)
# ------------------------------------------------------------
_UQ_BANKS = [
    ("Emergency Medicine and Trauma", "Emergency Medicine, Care and Triage"),
    ("Emergency Medicine and Trauma", "Anaphylaxis"),
    ("Emergency Medicine and Trauma", "Toxicology"),
    ("Emergency Medicine and Trauma", "Emergency Mental Health Presentations"),
    ("Emergency Medicine and Trauma", "Major Trauma"),
    ("Emergency Medicine and Trauma", "The Breathless Patient"),
    ("Emergency Medicine and Trauma", "Chest Pain"),
    ("Emergency Medicine and Trauma", "Arrhythmia"),
    ("Emergency Medicine and Trauma", "Altered Level of Consciousness"),
    ("Emergency Medicine and Trauma", "Stroke and Subarachnoid Haemorrhage"),
    ("Emergency Medicine and Trauma", "Traumatic Brain Injury"),
    ("Emergency Medicine and Trauma", "Procedures"),
    ("Emergency Medicine and Trauma", "Principles of Ultrasound in Critical Care"),
    ("Anaesthesia and Pain Management", "Introduction to Anaesthesia"),
    ("Anaesthesia and Pain Management", "Preoperative Anaesthetic Assessment"),
    ("Anaesthesia and Pain Management", "Postoperative Nausea and Vomiting"),
    ("Anaesthesia and Pain Management", "Maintaining Anaesthesia"),
    ("Anaesthesia and Pain Management", "Perioperative Fluid Therapy"),
    ("Anaesthesia and Pain Management", "Managing Acute Pain"),
    ("Anaesthesia and Pain Management", "Local and Regional Anaesthesia"),
    ("Intensive Care", "Introduction to the Intensive Care Unit"),
    ("Intensive Care", "The Deteriorating Patient"),
    ("Intensive Care", "Basic and Advanced Life Support"),
    ("Intensive Care", "Ethical Considerations in Critical Care"),
    ("Intensive Care", "Death and Organ Donation"),
    ("Intensive Care", "Arterial Blood Gas Interpretation"),
    ("Intensive Care", "Breathing"),
    ("Intensive Care", "Doctor and Wellbeing"),
]

# ------------------------------------------------------------
# EMED section topics (Broad Topic - Pathology)
# Auto-generated by build_emed_module.py
# ------------------------------------------------------------
_EMED_BANKS = [
    ("EMED", "Cardiology - Hypertension"),
    ("EMED", "Cardiology - Heart Failure"),
    ("EMED", "Cardiology - Hypercholesterolaemia"),
    ("EMED", "Cardiology - Cardiac Arrhythmia"),
    ("EMED", "Cardiology - Atrial Fibrillation"),
    ("EMED", "Cardiology - Acute Coronary Syndrome"),
    ("EMED", "Cardiology - Valvular Heart Disease"),
    ("EMED", "Cardiology - Deep Vein Thrombosis"),
    ("EMED", "Cardiology - Infective Endocarditis"),
    ("EMED", "Cardiology - Cardiac Tamponade / Pericardial Disease"),
    ("EMED", "Cardiology - General Cardiology"),
    ("EMED", "Dermatology - Rashes / Other Dermatoses"),
    ("EMED", "Dermatology - Non-melanoma Skin Cancer"),
    ("EMED", "Dermatology - Cellulitis / Skin Infection"),
    ("EMED", "Dermatology - Melanoma"),
    ("EMED", "Dermatology - Eczema / Atopic Dermatitis"),
    ("EMED", "Dermatology - Psoriasis"),
    ("EMED", "ENT - Neck Lump"),
    ("EMED", "ENT - Hearing Loss"),
    ("EMED", "ENT - Otitis Media / Externa"),
    ("EMED", "ENT - Sinusitis / Rhinitis"),
    ("EMED", "ENT - Vertigo / Vestibular"),
    ("EMED", "ENT - General ENT"),
    ("EMED", "Endocrinology - Type 2 Diabetes"),
    ("EMED", "Endocrinology - Sodium Disorders"),
    ("EMED", "Endocrinology - Thyroid - Hyperthyroidism / Graves"),
    ("EMED", "Endocrinology - Calcium / Parathyroid"),
    ("EMED", "Endocrinology - Thyroid Nodule / Cancer"),
    ("EMED", "Endocrinology - Adrenal - Addison / Insufficiency"),
    ("EMED", "Endocrinology - Type 1 Diabetes"),
    ("EMED", "Endocrinology - Thyroid - Hypothyroidism"),
    ("EMED", "Endocrinology - Pituitary Disease"),
    ("EMED", "Endocrinology - General Endocrinology"),
    ("EMED", "Endocrinology - Adrenal - Cushing"),
    ("EMED", "Gastroenterology - GORD"),
    ("EMED", "Gastroenterology - Cholecystitis / Biliary Colic"),
    ("EMED", "Gastroenterology - Upper GI Bleed"),
    ("EMED", "Gastroenterology - Bowel Obstruction"),
    ("EMED", "Gastroenterology - Inflammatory Bowel Disease"),
    ("EMED", "Gastroenterology - Hernia"),
    ("EMED", "Gastroenterology - Bowel Perforation / Acute Abdomen"),
    ("EMED", "Gastroenterology - Colorectal Cancer"),
    ("EMED", "Gastroenterology - Oesophageal Pathology"),
    ("EMED", "Gastroenterology - Cholangitis / Choledocholithiasis"),
    ("EMED", "Gastroenterology - Gastric Cancer"),
    ("EMED", "Gastroenterology - Appendicitis"),
    ("EMED", "Gastroenterology - Diverticular Disease"),
    ("EMED", "Gastroenterology - General Gastroenterology"),
    ("EMED", "General - Miscellaneous"),
    ("EMED", "Genetics - General Genetics"),
    ("EMED", "Gynaecology - Menstrual Disorders"),
    ("EMED", "Gynaecology - Cervical Screening / Cancer"),
    ("EMED", "Gynaecology - Ovarian Pathology"),
    ("EMED", "Gynaecology - Endometrial Pathology"),
    ("EMED", "Gynaecology - Menopause"),
    ("EMED", "Gynaecology - General Gynaecology"),
    ("EMED", "Haematology - Anaemia"),
    ("EMED", "Haematology - Bleeding / Coagulopathy"),
    ("EMED", "Haematology - Leukaemia"),
    ("EMED", "Haematology - Lymphoma"),
    ("EMED", "Haematology - Myeloma"),
    ("EMED", "Haematology - General Haematology"),
    ("EMED", "Hepatology - Alcoholic Liver Disease / Cirrhosis"),
    ("EMED", "Hepatology - Viral Hepatitis"),
    ("EMED", "Hepatology - Hepatocellular Carcinoma"),
    ("EMED", "Hepatology - Non-alcoholic Fatty Liver / MAFLD"),
    ("EMED", "Hepatology - Autoimmune / Cholestatic Liver Disease"),
    ("EMED", "Infectious Disease - Sexually Transmitted Infection"),
    ("EMED", "Infectious Disease - Tropical / Zoonotic"),
    ("EMED", "Infectious Disease - Gastroenteritis / Food Poisoning"),
    ("EMED", "Infectious Disease - Sepsis"),
    ("EMED", "Infectious Disease - HIV"),
    ("EMED", "Musculoskeletal - Vasculitis / Autoimmune"),
    ("EMED", "Musculoskeletal - Gout / Pseudogout"),
    ("EMED", "Musculoskeletal - Septic Arthritis / Osteomyelitis"),
    ("EMED", "Musculoskeletal - Rheumatoid Arthritis"),
    ("EMED", "Musculoskeletal - Osteoporosis"),
    ("EMED", "Musculoskeletal - Back Pain"),
    ("EMED", "Musculoskeletal - Fracture - Lower Limb / Pelvis"),
    ("EMED", "Musculoskeletal - Soft Tissue Injury"),
    ("EMED", "Musculoskeletal - Osteoarthritis"),
    ("EMED", "Musculoskeletal - Fracture - Upper Limb"),
    ("EMED", "Musculoskeletal - General Musculoskeletal"),
    ("EMED", "Neurology - Seizures / Epilepsy"),
    ("EMED", "Neurology - Dementia"),
    ("EMED", "Neurology - Parkinson Disease"),
    ("EMED", "Neurology - Multiple Sclerosis"),
    ("EMED", "Neurology - Meningitis"),
    ("EMED", "Neurology - Migraine / Headache"),
    ("EMED", "Neurology - Traumatic Brain Injury"),
    ("EMED", "Neurology - Spinal Cord Injury / Cauda Equina"),
    ("EMED", "Neurology - Haemorrhagic Stroke / SAH"),
    ("EMED", "Neurology - General Neurology"),
    ("EMED", "Neurology - Guillain-Barré / Peripheral Neuropathy"),
    ("EMED", "Neurology - Encephalitis"),
    ("EMED", "Neurology - Motor Neuron Disease"),
    ("EMED", "Obstetrics - Labour and Delivery"),
    ("EMED", "Obstetrics - Antenatal Care"),
    ("EMED", "Obstetrics - Ectopic Pregnancy / Early Pregnancy Loss"),
    ("EMED", "Obstetrics - Pre-eclampsia / HELLP"),
    ("EMED", "Obstetrics - General Obstetrics"),
    ("EMED", "Oncology - Breast Cancer"),
    ("EMED", "Oncology - Palliative Care"),
    ("EMED", "Oncology - General Oncology"),
    ("EMED", "Ophthalmology - Glaucoma"),
    ("EMED", "Ophthalmology - Red Eye"),
    ("EMED", "Ophthalmology - Macular Degeneration"),
    ("EMED", "Ophthalmology - General Ophthalmology"),
    ("EMED", "Paediatrics - Neonatal Care"),
    ("EMED", "Paediatrics - Paediatric Neurology / Development"),
    ("EMED", "Paediatrics - Paediatric Respiratory"),
    ("EMED", "Paediatrics - Paediatric Fever / Infection"),
    ("EMED", "Paediatrics - Paediatric Gastroenterology"),
    ("EMED", "Paediatrics - General Paediatrics"),
    ("EMED", "Professional Practice - Ethics / Consent"),
    ("EMED", "Professional Practice - Communication / Boundaries"),
    ("EMED", "Psychiatry - Schizophrenia / Psychosis"),
    ("EMED", "Psychiatry - Depression"),
    ("EMED", "Psychiatry - Anxiety Disorders"),
    ("EMED", "Psychiatry - Substance Use"),
    ("EMED", "Psychiatry - General Psychiatry"),
    ("EMED", "Psychiatry - Personality Disorder"),
    ("EMED", "Psychiatry - Bipolar Disorder"),
    ("EMED", "Renal - Glomerulonephritis / Nephrotic Syndrome"),
    ("EMED", "Renal - Acute Kidney Injury"),
    ("EMED", "Renal - Chronic Kidney Disease"),
    ("EMED", "Respiratory - Pneumonia"),
    ("EMED", "Respiratory - Tuberculosis"),
    ("EMED", "Respiratory - Asthma"),
    ("EMED", "Respiratory - Pulmonary Embolism"),
    ("EMED", "Respiratory - Lung Cancer"),
    ("EMED", "Respiratory - COPD"),
    ("EMED", "Respiratory - Interstitial Lung Disease"),
    ("EMED", "Respiratory - Pneumothorax"),
    ("EMED", "Respiratory - Pleural Disease"),
    ("EMED", "Respiratory - General Respiratory"),
    ("EMED", "Statistics / Evidence Based Medicine - Biostatistics"),
    ("EMED", "Surgery - Head and Neck"),
    ("EMED", "Surgery - Breast Lump / Benign Breast"),
    ("EMED", "Surgery - Wound / Post-op Complication"),
    ("EMED", "Trauma / Emergency - Toxicology"),
    ("EMED", "Trauma / Emergency - Cardiac Arrest / Resuscitation"),
    ("EMED", "Trauma / Emergency - Burns"),
    ("EMED", "Trauma / Emergency - Anaphylaxis"),
    ("EMED", "Trauma / Emergency - Drowning / Hypothermia / Environmental"),
    ("EMED", "Trauma / Emergency - Chest Trauma"),
    ("EMED", "Trauma / Emergency - Major Trauma"),
    ("EMED", "Trauma / Emergency - General Trauma / Emergency"),
    ("EMED", "Urology - Urinary Tract Infection"),
    ("EMED", "Urology - Testicular Pathology"),
    ("EMED", "Urology - Renal Colic / Stones"),
    ("EMED", "Urology - Prostate Cancer"),
    ("EMED", "Urology - Renal Cell Carcinoma"),
    ("EMED", "Urology - Benign Prostatic Hyperplasia"),
    ("EMED", "Urology - General Urology"),
    ("EMED", "Vascular - Abdominal Aortic Aneurysm"),
    ("EMED", "Vascular - Peripheral Arterial Disease"),
    ("EMED", "Vascular - General Vascular"),
]

SECTION_ORDER = [
    "Emergency Medicine and Trauma",
    "Anaesthesia and Pain Management",
    "Intensive Care",
    "Orthopaedics",
    "EMED",
]

SECTION_ICONS = {
    "Emergency Medicine and Trauma": "🚑",
    "Anaesthesia and Pain Management": "💉",
    "Intensive Care": "🫁",
    "Orthopaedics": "🦴",
    "EMED": "🎓",
}


def _slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def _build_topics():
    topics = []
    # Original UQ Critical Care topics (MCQ + VIVA)
    for section, topic_name in _UQ_BANKS:
        topics.append({
            "id": f"{_slug(section)}/{_slug(topic_name)}",
            "name": topic_name,
            "section": section,
            "mcq_bank": f"{_COURSE} :: {section} - {topic_name} (MCQ)",
            "viva_bank": f"{_COURSE} :: {section} - {topic_name} (VIVA)",
            "viva_source": "imported",
        })
    # Orthopaedics viva-only
    topics.append({
        "id": "orthopaedics/orthopaedic-trauma-framework",
        "name": "Orthopaedic Trauma Framework",
        "section": "Orthopaedics",
        "mcq_bank": None,
        "viva_bank": "Orthopaedic Trauma Framework (Viva)",
        "viva_source": "builtin",
    })
    # EMED topics (MCQ only, from emed_questions.EMED_BANKS)
    for section, topic_name in _EMED_BANKS:
        topics.append({
            "id": f"{_slug(section)}/{_slug(topic_name)}",
            "name": topic_name,
            "section": section,
            "mcq_bank": f"{_COURSE} :: EMED - {topic_name} (MCQ)",
            "viva_bank": None,
            "viva_source": None,
        })
    return topics


UQ_TOPICS = _build_topics()
_TOPIC_BY_ID = {t["id"]: t for t in UQ_TOPICS}


def sections():
    return SECTION_ORDER


def topics_for_section(section):
    return [t for t in UQ_TOPICS if t["section"] == section]


def get_topic(topic_id):
    return _TOPIC_BY_ID.get(topic_id)


def all_topic_ids():
    return [t["id"] for t in UQ_TOPICS]


if __name__ == "__main__":
    print(f"Sections: {len(SECTION_ORDER)}   Topics: {len(UQ_TOPICS)}")
    for sec in SECTION_ORDER:
        ts = topics_for_section(sec)
        print(f"  {sec:<40} topics={len(ts)}")
